version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    container_name: backend
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    container_name: frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge