name: Verify Docker Builds

on: [push, pull_request]

jobs:
  verify-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t backend .
      working-directory: ./api  # Changed from ./EVENTIFY-MAIN-5 to ./api

  verify-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t frontend .
      working-directory: ./client