name: Smoke Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    name: Run Smoke Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: 20 # Updated to current LTS
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Smoke Tests
        run: npx jest smoke.test.js --detectOpenHandles --forceExit
        env:
          MONGO_URI: ${{ secrets.MONGODB_ATLAS_URI_TEST }}
          JWT_SECRET: "test-secret-123"
          NODE_ENV: "test"

      # Only add this if you actually generate test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: smoke-test-results
          path: |
            test-results/
            coverage/