name: CI Pipeline
on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Fix permissions
        run: sudo chmod -R 777 node_modules
      
      - name: Run tests
        run: npx jest --detectOpenHandles --forceExit --coverage
        env:
          MONGO_URI: ${{ secrets.MONGODB_ATLAS_URI_TEST }}
          JWT_SECRET: "test-secret-123"
